name: check build

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run : echo "Ei, deploy!"

  other_thing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run : echo "Ei, Other Thing!"


